services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false

    # Add tag for interface
    _instanceof:
        Zyos\InstallBundle\ValidatorsInterface:
            lazy: true
            public: true
            tags: [ 'zyos_install.validators' ]

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    Zyos\InstallBundle\:
        resource: '../../../src/*'
        exclude: '../../../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'
        public: false

    # Handlers for validations
    Zyos\InstallBundle\ValidatorsHandler:
        calls:
            - setIterable: [!tagged { tag: 'zyos_install.validators', default_index_method: 'getName' }]